<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter message_user-message</name>
   <tag></tag>
   <elementGuidId>b0d7815f-225a-4637-8116-401674b859a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da4bab53-5d56-44d6-a7c8-7283d2ed9320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dac0f7e6-27a6-445d-aa62-5e78c0250623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ba096ade-236b-4a5d-8583-d32a88d88ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>9d53f05e-d15c-485b-bcbd-e0d76439022e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter your Message</value>
      <webElementGuid>d3b2a797-7b31-4720-94c0-b86c9bdc517a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-message</value>
      <webElementGuid>2729d39b-4bd6-4b55-b154-82f6c5a076cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;get-input&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;user-message&quot;]</value>
      <webElementGuid>e5e72bfa-598f-49c1-9c99-71f3866af78d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user-message']</value>
      <webElementGuid>993e859b-699e-452b-bf8b-77e8e5f3942f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='get-input']/div/input</value>
      <webElementGuid>96b1fb42-e949-494e-bb1a-9c346c31a061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>48debc08-fb51-4f0f-84e7-801641f6dae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Please enter your Message' and @id = 'user-message']</value>
      <webElementGuid>781ce28b-7bca-47ce-9b32-f6debeed123e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
